name: lbi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - ninja
  - cmake
  - packaging
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.9.1
      - triton==3.5.1
      - tilelang==0.1.12
      - numpy
      - einops
      - matplotlib
      - pytest
      - datasets
      - huggingface_hub
      - transformers
