from .autograd import AutogradEngine, autograd_backward_step
from .base import ADEngine, ADResult, GradMap, LBIBackwardResult, ScanBackpropModel, assign_grad_map, collect_named_grads, store_named_grads
from .local_vjp import (
    LocalVJPProvider,
    NativeLocalVJPProvider,
    RegionBackwardResult,
    TorchAutogradLocalVJPProvider,
    native_initial_backward,
    native_region_backward,
    reduce_region_results,
)
from .pullbacks import (
    ForwardModeInterfacePullbackProvider,
    InterfacePullbackProvider,
    NativeInterfacePullbackProvider,
    TorchGraphInterfacePullbackProvider,
    TorchRecomputeInterfacePullbackProvider,
    build_interface_pullback_provider,
    interface_state_jacobian_for_region_forward,
    interface_state_jacobian_t_for_region,
    materialize_interface_state_jacobian_t_graph,
    materialize_interface_state_jacobian_t_native,
    materialize_interface_state_jacobian_t_recompute,
)
from .reference_scan import ReferenceScanEngine, ScanADEngine, lbi_reference_scan_backward_step, lbi_scan_backward_step
from .suffix_scan import (
    apply_jacobian_t,
    compose_suffix_jacobian_t,
    propagate_state_adjoint_by_autograd_chain,
    propagate_state_adjoint_from_last_region_input,
    propagate_state_adjoint_with_jacobian_scan,
)

__all__ = [
    "ADEngine",
    "ADResult",
    "AutogradEngine",
    "GradMap",
    "ForwardModeInterfacePullbackProvider",
    "InterfacePullbackProvider",
    "interface_state_jacobian_for_region_forward",
    "LBIBackwardResult",
    "LocalVJPProvider",
    "NativeLocalVJPProvider",
    "ReferenceScanEngine",
    "ScanADEngine",
    "ScanBackpropModel",
    "TorchAutogradLocalVJPProvider",
    "NativeInterfacePullbackProvider",
    "RegionBackwardResult",
    "TorchGraphInterfacePullbackProvider",
    "TorchRecomputeInterfacePullbackProvider",
    "assign_grad_map",
    "autograd_backward_step",
    "apply_jacobian_t",
    "build_interface_pullback_provider",
    "collect_named_grads",
    "compose_suffix_jacobian_t",
    "interface_state_jacobian_t_for_region",
    "lbi_reference_scan_backward_step",
    "lbi_scan_backward_step",
    "materialize_interface_state_jacobian_t_graph",
    "materialize_interface_state_jacobian_t_native",
    "materialize_interface_state_jacobian_t_recompute",
    "native_initial_backward",
    "native_region_backward",
    "reduce_region_results",
    "propagate_state_adjoint_by_autograd_chain",
    "propagate_state_adjoint_from_last_region_input",
    "propagate_state_adjoint_with_jacobian_scan",
    "store_named_grads",
]
