#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Sequence

import matplotlib.pyplot as plt
import numpy as np

"""Optional message-ablation plotting utilities.

Main paper CE-vs-token plots are generated by scripts.plot_training_curves.
"""

@dataclass
class AblationRun:
    run_dir: Path
    variant: str
    backbone: str
    seed: int
    metrics_rows: List[Dict[str, str]]


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot message-ablation curves from one or more LBI run roots.")
    p.add_argument("run_roots", nargs="+", type=Path, help="Run roots or per-regime run directories.")
    p.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory to write plots into. Defaults to <first_run_root>/ablation_plots.",
    )
    p.add_argument(
        "--dpi",
        type=int,
        default=150,
        help="Output DPI for saved figures.",
    )
    p.add_argument(
        "--include-variant-regex",
        type=str,
        default="",
        help="Optional regex applied to the run variant directory name.",
    )
    p.add_argument(
        "--exclude-variant-regex",
        type=str,
        default="",
        help="Optional regex applied to the run variant directory name after include filtering.",
    )
    return p.parse_args()


def _load_metrics_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _to_float(value: str | float | int | None) -> float | None:
    if value == "" or value is None:
        return None
    x = float(value)
    if math.isnan(x) or math.isinf(x):
        return None
    return x


def _discover_native_run_dirs(paths: Sequence[Path]) -> List[Path]:
    discovered: List[Path] = []
    for raw_path in paths:
        path = raw_path.resolve()
        if not path.exists():
            raise FileNotFoundError(f"path does not exist: {path}")
        if (path / "metrics.csv").exists():
            discovered.append(path)
            continue
        native_dir = path / "native_region_interface"
        if (native_dir / "metrics.csv").exists():
            discovered.append(native_dir)
            continue
        run_dirs = sorted(p.parent for p in path.rglob("metrics.csv") if p.is_file())
        for run_dir in run_dirs:
            summary_path = run_dir / "summary.json"
            if not summary_path.exists():
                continue
            summary = _load_json(summary_path)
            if summary.get("regime") == "native_region_interface":
                discovered.append(run_dir)
    if not discovered:
        raise RuntimeError("no native_region_interface run directories with metrics.csv found")
    return discovered


def _variant_from_native_run_dir(run_dir: Path, config: Dict[str, Any]) -> str:
    if run_dir.name == "native_region_interface":
        return run_dir.parent.name
    run_name = str(config.get("run_name", ""))
    if run_name:
        return run_name
    msg = config.get("message_dim", "unknown")
    return f"lbi_r{msg}_seed{config.get('seed', 'unknown')}"


def _load_runs(
    paths: Sequence[Path],
    *,
    include_variant_regex: str = "",
    exclude_variant_regex: str = "",
) -> List[AblationRun]:
    runs: List[AblationRun] = []
    include_re = re.compile(include_variant_regex) if include_variant_regex else None
    exclude_re = re.compile(exclude_variant_regex) if exclude_variant_regex else None
    for run_dir in _discover_native_run_dirs(paths):
        config = _load_json(run_dir / "config.json")
        variant = _variant_from_native_run_dir(run_dir, config)
        if include_re is not None and include_re.search(variant) is None:
            continue
        if exclude_re is not None and exclude_re.search(variant) is not None:
            continue
        runs.append(
            AblationRun(
                run_dir=run_dir,
                variant=variant,
                backbone=str(config.get("backbone", "unknown")),
                seed=int(config.get("seed", -1)),
                metrics_rows=_load_metrics_csv(run_dir / "metrics.csv"),
            )
        )
    if not runs:
        raise RuntimeError("no matching native_region_interface runs found for the requested filters")
    return runs


def _split_names(rows: Sequence[Dict[str, str]]) -> List[str]:
    names = {"val"}
    names.update(row["split"] for row in rows if row.get("split", "").startswith("val_"))
    return sorted(names, key=lambda name: (name != "val", name))


def _aggregate_series(runs: Sequence[AblationRun], *, split: str) -> List[Dict[str, float]]:
    by_x: Dict[float, List[float]] = {}
    for run in runs:
        for row in run.metrics_rows:
            if row.get("split") != split:
                continue
            x_val = _to_float(row.get("tokens_seen"))
            y_val = _to_float(row.get("ce_loss"))
            if x_val is None or y_val is None:
                continue
            by_x.setdefault(x_val, []).append(y_val)
    rows = []
    for x_val in sorted(by_x.keys()):
        ys = by_x[x_val]
        rows.append(
            {
                "x": x_val,
                "mean": float(np.mean(ys)),
                "std": float(np.std(ys)) if len(ys) > 1 else 0.0,
                "count": float(len(ys)),
            }
        )
    return rows


def _write_csv(path: Path, rows: Sequence[Dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _plot_backbone_curves(backbone: str, runs: Sequence[AblationRun], *, output_dir: Path, dpi: int) -> List[Dict[str, Any]]:
    split_names = _split_names(runs[0].metrics_rows)
    fig, ax = plt.subplots(figsize=(9, 5))
    colors = plt.get_cmap("tab10")
    summary_rows: List[Dict[str, Any]] = []
    plotted = False
    for idx, split_name in enumerate(split_names):
        rows = _aggregate_series(runs, split=split_name)
        if not rows:
            continue
        plotted = True
        xs = [row["x"] for row in rows]
        ys = [row["mean"] for row in rows]
        std = [row["std"] for row in rows]
        label = "val" if split_name == "val" else split_name.replace("val_", "")
        color = colors(idx % 10)
        linestyle = "--" if split_name == "val" else "-"
        ax.plot(xs, ys, color=color, linestyle=linestyle, label=label)
        ax.fill_between(xs, np.array(ys) - np.array(std), np.array(ys) + np.array(std), color=color, alpha=0.15)
        summary_rows.append(
            {
                "backbone": backbone,
                "split": split_name,
                "num_runs": len(runs),
                "mean_final_ce": float(rows[-1]["mean"]),
                "std_final_ce": float(rows[-1]["std"]),
            }
        )
    if plotted:
        ax.set_title(f"{backbone} Message Ablations")
        ax.set_xlabel("Tokens Seen")
        ax.set_ylabel("Validation Cross-Entropy")
        ax.grid(True, alpha=0.3)
        ax.legend()
        fig.tight_layout()
        fig.savefig(output_dir / f"{backbone}_ablation_ce_vs_tokens.png", dpi=dpi)
    plt.close(fig)

    if summary_rows:
        labels = ["val" if row["split"] == "val" else row["split"].replace("val_", "") for row in summary_rows]
        means = np.array([row["mean_final_ce"] for row in summary_rows], dtype=np.float64)
        std = np.array([row["std_final_ce"] for row in summary_rows], dtype=np.float64)
        fig, ax = plt.subplots(figsize=(max(6.0, 1.2 * len(labels)), 4.2))
        x = np.arange(len(labels), dtype=np.float64)
        ax.bar(x, means, yerr=std, capsize=4)
        ax.set_title(f"{backbone} Final Ablation CE")
        ax.set_ylabel("Validation Cross-Entropy")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=20, ha="right")
        ax.grid(True, axis="y", alpha=0.3)
        fig.tight_layout()
        fig.savefig(output_dir / f"{backbone}_ablation_final_ce.png", dpi=dpi)
        plt.close(fig)
    return summary_rows


def generate_message_ablation_plots(
    run_roots: Sequence[Path],
    *,
    output_dir: Path | None = None,
    dpi: int = 150,
    include_variant_regex: str = "",
    exclude_variant_regex: str = "",
) -> Path:
    runs = _load_runs(
        run_roots,
        include_variant_regex=include_variant_regex,
        exclude_variant_regex=exclude_variant_regex,
    )
    base_root = run_roots[0].resolve()
    default_dir = base_root / "ablation_plots" if base_root.is_dir() else base_root.parent / "ablation_plots"
    out_dir = (output_dir or default_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    summary_rows: List[Dict[str, Any]] = []
    by_backbone: Dict[str, List[AblationRun]] = {}
    for run in runs:
        by_backbone.setdefault(run.backbone, []).append(run)
    for backbone, backbone_runs in sorted(by_backbone.items()):
        summary_rows.extend(_plot_backbone_curves(backbone, backbone_runs, output_dir=out_dir, dpi=dpi))
    _write_csv(out_dir / "ablation_summary.csv", summary_rows)
    (out_dir / "ablation_summary.json").write_text(json.dumps(summary_rows, indent=2) + "\n", encoding="utf-8")
    return out_dir


def main() -> None:
    args = _parse_args()
    out_dir = generate_message_ablation_plots(
        args.run_roots,
        output_dir=args.output_dir,
        dpi=args.dpi,
        include_variant_regex=args.include_variant_regex,
        exclude_variant_regex=args.exclude_variant_regex,
    )
    print(f"wrote ablation plots to {out_dir}")


if __name__ == "__main__":
    main()
